### ISSUE TITLE
Toolchain - building issues

### ISSUE THREAD

**Issue by VitRuzicka** [mean00/lnDSO150#3]
Hi, I think I managed to install the toolchain with xpm but I cannot seem to "give the path to the toolchain". I thought I have to edit it in the platformConfig.cmake file on line 20 but seemingly without any effect.

Thanks, Vit

**Comment by mean00** [comment]
Hi
Yes , assuming you are on linux (or similar) that should be enough.
With one caveat : if you touch mcuConfig.cmake or platformSettings.cmake you HAVE to cleanup the binary folder
and redo the cmake step from the beginning/empty build tree.

**Comment by mean00** [comment]
i can also attach a binary for testing purpose , just give me your flavor (original JYETECH or FNIRSI clone)

**Comment by VitRuzicka** [comment]
> i can also attach a binary for testing purpose , just give me your flavor (original JYETECH or FNIRSI clone)

That would be great since I still cannot make the toolchain work. I have the FNIRSI clone with CH32 chip.

Thanks, Vit

**Comment by VitRuzicka** [comment]
Works perfectly, thank you very much. Glad to see active development. 
Also, where is the donate button? :)

Vit
